name: xarray-spatial

dependencies:
  - python >=3.6
  - datashader
  - numpy
  - pandas
  - xarray
  - dask
  - rasterio
  - rioxarray
  - satsearch
  - azure
  - pystac-client
  - planetary-computer
  - geopandas
  - spatialpandas
  - xarray-spatial
  - setuptools
  - pip
  - pip3:
    - stackstac
