name: xarray-spatial
channels:
  - anaconda
  - conda-forge
  - pyviz
dependencies:
  - python >=3.6
  - datashader
  - numpy
  - pandas
  - xarray
  - dask
  - rasterio
  - rioxarray
  - satsearch
  - azure
  - pystac-client
  - planetary-computer
  - geopandas
  - spatialpandas
  - xarray-spatial
  - pip
    pip:
    - stackstac
