name: xarray-spatial
channels:
  - conda-forge
  - pyviz
  - anaconda
dependencies:
  - python >=3.6
  - datashader
  - numpy
  - pandas
  - xarray
  - dask
  - rasterio
  - rioxarray
  - satsearch
  - azure
  - pystac-client
  - planetary-computer
  - geopandas
  - spatialpandas
  - xarray-spatial
  - pip
  - pip:
    - stackstac ==0.2.1
