name: xarray-spatial
channels:
  - anaconda
  - conda-forge
  - pyviz
dependencies:
  - datashader
  - numpy
  - pandas
  - xarray
  - dask
  - rasterio
  - rioxarray
  - stackstac
  - satsearch
  - azure
  - pystac_client
  - planetary_computer
  - geopandas
  - spatialpandas
  - xarray-spatial
